services:
  - type: web
    name: waste-sorting-client
    env: static
    buildCommand: ./build.sh
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://your-server-name.onrender.com 